"""add allowed_environments

Revision ID: 0255a0347193
Revises: f7b8cd30756e
Create Date: 2026-02-25 00:39:56.081558+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0255a0347193'
down_revision = 'f7b8cd30756e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
