"""add avatar_image_path to user

Revision ID: f7b8cd30756e
Revises: 94bf73cbcc50
Create Date: 2026-02-24 23:42:35.961051+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b8cd30756e'
down_revision = '94bf73cbcc50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_image_path', sa.String(length=255), nullable=True, comment='头像图片路径'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_image_path')
    # ### end Alembic commands ###
