"""init_db

Revision ID: 94bf73cbcc50
Revises: 
Create Date: 2026-02-24 17:17:09.107453+08:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bf73cbcc50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False, comment='公告ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容（支持富文本）'),
    sa.Column('announcement_type', sa.String(length=50), nullable=False, comment='公告类型: system/quality_warning/document_update'),
    sa.Column('importance', sa.String(length=20), nullable=False, comment='重要程度: normal/important'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活（可用于撤回公告）'),
    sa.Column('published_at', sa.DateTime(), nullable=False, comment='发布时间'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='过期时间（可选，过期后自动隐藏）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_announcement_type'), 'announcements', ['announcement_type'], unique=False)
    op.create_index(op.f('ix_announcements_expires_at'), 'announcements', ['expires_at'], unique=False)
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_index(op.f('ix_announcements_importance'), 'announcements', ['importance'], unique=False)
    op.create_index(op.f('ix_announcements_is_active'), 'announcements', ['is_active'], unique=False)
    op.create_index(op.f('ix_announcements_published_at'), 'announcements', ['published_at'], unique=False)
    op.create_table('audit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='审核类型: system_audit (IATF16949), process_audit (VDA6.3), product_audit (VDA6.5), customer_audit'),
    sa.Column('audit_name', sa.String(length=255), nullable=False, comment='审核名称'),
    sa.Column('planned_date', sa.DateTime(), nullable=False, comment='计划审核日期'),
    sa.Column('auditor_id', sa.Integer(), nullable=False, comment='主审核员ID'),
    sa.Column('auditee_dept', sa.String(length=100), nullable=False, comment='被审核部门'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: planned, in_progress, completed, postponed, cancelled'),
    sa.Column('postpone_reason', sa.Text(), nullable=True, comment='延期原因'),
    sa.Column('postpone_approved_by', sa.Integer(), nullable=True, comment='延期批准人ID'),
    sa.Column('postpone_approved_at', sa.DateTime(), nullable=True, comment='延期批准时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_plans_audit_type'), 'audit_plans', ['audit_type'], unique=False)
    op.create_index(op.f('ix_audit_plans_auditor_id'), 'audit_plans', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_audit_plans_id'), 'audit_plans', ['id'], unique=False)
    op.create_index(op.f('ix_audit_plans_planned_date'), 'audit_plans', ['planned_date'], unique=False)
    op.create_index(op.f('ix_audit_plans_status'), 'audit_plans', ['status'], unique=False)
    op.create_table('audit_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False, comment='模板名称'),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='适用审核类型: system_audit, process_audit, product_audit, custom'),
    sa.Column('checklist_items', sa.JSON(), nullable=False, comment='检查表条款列表 (JSON格式，包含条款编号、描述、评分标准等)'),
    sa.Column('scoring_rules', sa.JSON(), nullable=False, comment='评分规则 (JSON格式，包含评分方法、等级划分、降级规则等)'),
    sa.Column('description', sa.Text(), nullable=True, comment='模板描述'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, comment='是否为系统内置模板'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_templates_audit_type'), 'audit_templates', ['audit_type'], unique=False)
    op.create_index(op.f('ix_audit_templates_id'), 'audit_templates', ['id'], unique=False)
    op.create_index(op.f('ix_audit_templates_is_active'), 'audit_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_audit_templates_template_name'), 'audit_templates', ['template_name'], unique=True)
    op.create_table('barcode_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False, comment='物料编码'),
    sa.Column('validation_rules', sa.JSON(), nullable=True, comment='校验规则'),
    sa.Column('regex_pattern', sa.String(length=200), nullable=True, comment='正则表达式'),
    sa.Column('is_unique_check', sa.Boolean(), nullable=False, comment='是否启用唯一性校验'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID（SQE）'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_validations_id'), 'barcode_validations', ['id'], unique=False)
    op.create_index(op.f('ix_barcode_validations_material_code'), 'barcode_validations', ['material_code'], unique=False)
    op.create_table('cost_analysis',
    sa.Column('id', sa.Integer(), nullable=False, comment='分析记录ID'),
    sa.Column('analysis_type', sa.String(length=50), nullable=True, comment='分析类型: monthly/quarterly/yearly/supplier/product'),
    sa.Column('analysis_period', sa.String(length=50), nullable=True, comment='分析周期（如：2024-01, 2024-Q1, 2024）'),
    sa.Column('total_cost', sa.Numeric(precision=15, scale=2), nullable=True, comment='总成本金额'),
    sa.Column('analysis_result', sa.JSON(), nullable=True, comment='分析结果详情（JSON格式）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_analysis_analysis_period'), 'cost_analysis', ['analysis_period'], unique=False)
    op.create_index(op.f('ix_cost_analysis_analysis_type'), 'cost_analysis', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_cost_analysis_id'), 'cost_analysis', ['id'], unique=False)
    op.create_table('customer_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False, comment='客户名称'),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='审核类型: system, process, product, qualification, potential_supplier'),
    sa.Column('audit_date', sa.DateTime(), nullable=False, comment='审核日期'),
    sa.Column('final_result', sa.String(length=50), nullable=False, comment='最终结果: passed, conditional_passed, failed, pending'),
    sa.Column('score', sa.Integer(), nullable=True, comment='审核得分 (如果客户提供)'),
    sa.Column('external_issue_list_path', sa.String(length=500), nullable=True, comment='客户提供的问题整改清单文件路径 (Excel等)'),
    sa.Column('internal_contact', sa.String(length=255), nullable=True, comment='内部接待人员'),
    sa.Column('audit_report_path', sa.String(length=500), nullable=True, comment='审核报告文件路径'),
    sa.Column('summary', sa.Text(), nullable=True, comment='审核总结'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: completed, issue_open, issue_closed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_audits_audit_date'), 'customer_audits', ['audit_date'], unique=False)
    op.create_index(op.f('ix_customer_audits_customer_name'), 'customer_audits', ['customer_name'], unique=False)
    op.create_index(op.f('ix_customer_audits_id'), 'customer_audits', ['id'], unique=False)
    op.create_index(op.f('ix_customer_audits_status'), 'customer_audits', ['status'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_key', sa.String(length=100), nullable=False, comment='功能唯一标识键'),
    sa.Column('feature_name', sa.String(length=200), nullable=False, comment='功能名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='功能描述'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('scope', sa.Enum('GLOBAL', 'WHITELIST', name='featureflagscope', native_enum=False, length=20), nullable=False, comment='作用域'),
    sa.Column('whitelist_user_ids', sa.JSON(), nullable=True, comment='白名单用户ID列表'),
    sa.Column('whitelist_supplier_ids', sa.JSON(), nullable=True, comment='白名单供应商ID列表'),
    sa.Column('environment', sa.Enum('STABLE', 'PREVIEW', name='featureflagenvironment', native_enum=False, length=20), nullable=False, comment='环境标识'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_environment'), 'feature_flags', ['environment'], unique=False)
    op.create_index(op.f('ix_feature_flags_feature_key'), 'feature_flags', ['feature_key'], unique=True)
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.create_table('ims_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sync_type', sa.Enum('INCOMING_INSPECTION', 'PRODUCTION_OUTPUT', 'PROCESS_TEST', 'PROCESS_DEFECTS', 'SHIPMENT_DATA', 'FIRST_PASS_TEST', 'IQC_RESULTS', 'SPECIAL_APPROVAL', name='synctype', native_enum=False, length=50), nullable=False, comment='同步类型'),
    sa.Column('sync_date', sa.Date(), nullable=False, comment='同步日期'),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'PARTIAL', 'IN_PROGRESS', name='syncstatus', native_enum=False, length=20), nullable=False, comment='同步状态'),
    sa.Column('records_count', sa.Integer(), nullable=False, comment='同步记录数量'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息详情'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='同步开始时间'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='同步结束时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ims_sync_logs_id'), 'ims_sync_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ims_sync_logs_status'), 'ims_sync_logs', ['status'], unique=False)
    op.create_index(op.f('ix_ims_sync_logs_sync_date'), 'ims_sync_logs', ['sync_date'], unique=False)
    op.create_index(op.f('ix_ims_sync_logs_sync_type'), 'ims_sync_logs', ['sync_type'], unique=False)
    op.create_table('instrument_calibrations',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('instrument_code', sa.String(length=100), nullable=True, comment='仪器编码'),
    sa.Column('instrument_name', sa.String(length=255), nullable=True, comment='仪器名称'),
    sa.Column('calibration_date', sa.Date(), nullable=True, comment='校准日期'),
    sa.Column('next_calibration_date', sa.Date(), nullable=True, comment='下次校准日期'),
    sa.Column('calibration_status', sa.String(length=20), nullable=True, comment='校准状态: valid/expired/frozen'),
    sa.Column('calibration_certificate_path', sa.String(length=500), nullable=True, comment='校准证书文件路径'),
    sa.Column('responsible_user_id', sa.Integer(), nullable=True, comment='责任人用户ID'),
    sa.Column('msa_report_path', sa.String(length=500), nullable=True, comment='MSA分析报告文件路径'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instrument_calibrations_calibration_status'), 'instrument_calibrations', ['calibration_status'], unique=False)
    op.create_index(op.f('ix_instrument_calibrations_id'), 'instrument_calibrations', ['id'], unique=False)
    op.create_index(op.f('ix_instrument_calibrations_instrument_code'), 'instrument_calibrations', ['instrument_code'], unique=False)
    op.create_index(op.f('ix_instrument_calibrations_next_calibration_date'), 'instrument_calibrations', ['next_calibration_date'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False, comment='仪器ID'),
    sa.Column('instrument_code', sa.String(length=100), nullable=True, comment='仪器编码（唯一标识）'),
    sa.Column('instrument_name', sa.String(length=255), nullable=True, comment='仪器名称'),
    sa.Column('instrument_type', sa.String(length=50), nullable=True, comment='仪器类型: measuring/testing/calibration/inspection/other'),
    sa.Column('calibration_date', sa.Date(), nullable=True, comment='最近校准日期'),
    sa.Column('next_calibration_date', sa.Date(), nullable=True, comment='下次校准日期'),
    sa.Column('calibration_cert_path', sa.String(length=500), nullable=True, comment='校准证书文件路径'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='仪器状态: active/expired/frozen/retired'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人用户ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人用户ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_code'), 'instruments', ['instrument_code'], unique=True)
    op.create_index(op.f('ix_instruments_instrument_type'), 'instruments', ['instrument_type'], unique=False)
    op.create_index(op.f('ix_instruments_next_calibration_date'), 'instruments', ['next_calibration_date'], unique=False)
    op.create_index(op.f('ix_instruments_status'), 'instruments', ['status'], unique=False)
    op.create_table('lesson_learned_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_title', sa.String(length=200), nullable=False, comment='经验教训标题'),
    sa.Column('lesson_content', sa.Text(), nullable=False, comment='经验教训详细内容'),
    sa.Column('source_module', sa.Enum('SUPPLIER_QUALITY', 'PROCESS_QUALITY', 'CUSTOMER_QUALITY', 'MANUAL', name='sourcemodule', native_enum=False, length=50), nullable=False, comment='来源模块'),
    sa.Column('source_record_id', sa.Integer(), nullable=True, comment='来源记录ID（8D报告ID等）'),
    sa.Column('root_cause', sa.Text(), nullable=False, comment='根本原因'),
    sa.Column('preventive_action', sa.Text(), nullable=False, comment='预防措施'),
    sa.Column('applicable_scenarios', sa.Text(), nullable=True, comment='适用场景描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_learned_library_id'), 'lesson_learned_library', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_learned_library_is_active'), 'lesson_learned_library', ['is_active'], unique=False)
    op.create_table('new_product_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=50), nullable=False, comment='项目代码'),
    sa.Column('project_name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('product_type', sa.String(length=100), nullable=True, comment='产品类型'),
    sa.Column('project_manager', sa.String(length=100), nullable=True, comment='项目经理'),
    sa.Column('project_manager_id', sa.Integer(), nullable=True, comment='项目经理用户ID'),
    sa.Column('current_stage', sa.Enum('CONCEPT', 'DESIGN', 'DEVELOPMENT', 'VALIDATION', 'TRIAL_PRODUCTION', 'SOP', 'CLOSED', name='projectstage', native_enum=False, length=50), nullable=False, comment='当前阶段'),
    sa.Column('status', sa.Enum('ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus', native_enum=False, length=20), nullable=False, comment='项目状态'),
    sa.Column('planned_sop_date', sa.DateTime(), nullable=True, comment='计划SOP日期'),
    sa.Column('actual_sop_date', sa.DateTime(), nullable=True, comment='实际SOP日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_product_projects_current_stage'), 'new_product_projects', ['current_stage'], unique=False)
    op.create_index(op.f('ix_new_product_projects_id'), 'new_product_projects', ['id'], unique=False)
    op.create_index(op.f('ix_new_product_projects_project_code'), 'new_product_projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_new_product_projects_status'), 'new_product_projects', ['status'], unique=False)
    op.create_table('quality_costs',
    sa.Column('id', sa.Integer(), nullable=False, comment='成本记录ID'),
    sa.Column('cost_type', sa.String(length=50), nullable=True, comment='成本类型: internal_failure/external_failure/appraisal/prevention'),
    sa.Column('cost_category', sa.String(length=100), nullable=True, comment='成本细分类别（如：报废、返工、索赔等）'),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='成本金额'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='货币单位（默认人民币）'),
    sa.Column('related_object_type', sa.String(length=50), nullable=True, comment='关联业务类型: scar/customer_complaint/scrap/rework等'),
    sa.Column('related_object_id', sa.Integer(), nullable=True, comment='关联业务对象ID'),
    sa.Column('cost_date', sa.Date(), nullable=True, comment='成本发生日期'),
    sa.Column('fiscal_year', sa.Integer(), nullable=True, comment='财年'),
    sa.Column('fiscal_month', sa.Integer(), nullable=True, comment='财月'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_costs_cost_date'), 'quality_costs', ['cost_date'], unique=False)
    op.create_index(op.f('ix_quality_costs_cost_type'), 'quality_costs', ['cost_type'], unique=False)
    op.create_index(op.f('ix_quality_costs_fiscal_month'), 'quality_costs', ['fiscal_month'], unique=False)
    op.create_index(op.f('ix_quality_costs_fiscal_year'), 'quality_costs', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_quality_costs_id'), 'quality_costs', ['id'], unique=False)
    op.create_index(op.f('ix_quality_costs_related_object_id'), 'quality_costs', ['related_object_id'], unique=False)
    op.create_index(op.f('ix_quality_costs_related_object_type'), 'quality_costs', ['related_object_type'], unique=False)
    op.create_table('smtp_configs',
    sa.Column('id', sa.Integer(), nullable=False, comment='配置ID'),
    sa.Column('config_name', sa.String(length=100), nullable=False, comment='配置名称（唯一标识）'),
    sa.Column('smtp_host', sa.String(length=255), nullable=False, comment='SMTP服务器地址'),
    sa.Column('smtp_port', sa.Integer(), nullable=False, comment='SMTP端口（通常为25/465/587）'),
    sa.Column('smtp_user', sa.String(length=255), nullable=False, comment='SMTP用户名'),
    sa.Column('smtp_password_encrypted', sa.Text(), nullable=False, comment='SMTP密码（加密存储）'),
    sa.Column('use_tls', sa.Boolean(), nullable=False, comment='是否使用TLS加密'),
    sa.Column('from_email', sa.String(length=255), nullable=False, comment='发件人邮箱地址'),
    sa.Column('from_name', sa.String(length=100), nullable=True, comment='发件人显示名称'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否为当前激活配置'),
    sa.Column('last_test_at', sa.DateTime(), nullable=True, comment='最后测试时间'),
    sa.Column('last_test_result', sa.String(length=20), nullable=True, comment='最后测试结果: success/failed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_name')
    )
    op.create_index(op.f('ix_smtp_configs_id'), 'smtp_configs', ['id'], unique=False)
    op.create_index(op.f('ix_smtp_configs_is_active'), 'smtp_configs', ['is_active'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False, comment='供应商名称'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='供应商代码'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='联系人'),
    sa.Column('contact_email', sa.String(length=100), nullable=True, comment='联系邮箱'),
    sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='联系电话'),
    sa.Column('iso9001_cert', sa.String(length=255), nullable=True, comment='ISO9001 证书路径'),
    sa.Column('iso9001_expiry', sa.DateTime(), nullable=True, comment='ISO9001 到期日期'),
    sa.Column('iatf16949_cert', sa.String(length=255), nullable=True, comment='IATF16949 证书路径'),
    sa.Column('iatf16949_expiry', sa.DateTime(), nullable=True, comment='IATF16949 到期日期'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', name='supplierstatus', native_enum=False, length=20), nullable=False, comment='供应商状态'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_code'), 'suppliers', ['code'], unique=True)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False, comment='配置键（唯一标识）'),
    sa.Column('config_value', sa.JSON(), nullable=False, comment='配置值（JSON 格式）'),
    sa.Column('config_type', sa.String(length=50), nullable=False, comment='配置数据类型（string/number/boolean/object/array）'),
    sa.Column('description', sa.Text(), nullable=True, comment='配置项描述说明'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='配置分类'),
    sa.Column('validation_rule', sa.JSON(), nullable=True, comment='验证规则（JSON Schema）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='最后更新人ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('audit_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_plan_id', sa.Integer(), nullable=False, comment='审核计划ID'),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='审核模板ID'),
    sa.Column('audit_date', sa.DateTime(), nullable=False, comment='实际审核日期'),
    sa.Column('auditor_id', sa.Integer(), nullable=False, comment='主审核员ID'),
    sa.Column('audit_team', sa.JSON(), nullable=True, comment='审核组成员列表 (JSON格式)'),
    sa.Column('checklist_results', sa.JSON(), nullable=False, comment='检查表结果 (JSON格式，包含每个条款的评分、证据照片等)'),
    sa.Column('final_score', sa.Integer(), nullable=True, comment='最终得分 (百分制)'),
    sa.Column('grade', sa.String(length=10), nullable=True, comment='等级评定 (A/B/C/D)'),
    sa.Column('audit_report_path', sa.String(length=500), nullable=True, comment='审核报告文件路径'),
    sa.Column('summary', sa.Text(), nullable=True, comment='审核总结'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: draft, completed, nc_open, nc_closed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['audit_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_executions_audit_date'), 'audit_executions', ['audit_date'], unique=False)
    op.create_index(op.f('ix_audit_executions_audit_plan_id'), 'audit_executions', ['audit_plan_id'], unique=False)
    op.create_index(op.f('ix_audit_executions_auditor_id'), 'audit_executions', ['auditor_id'], unique=False)
    op.create_index(op.f('ix_audit_executions_id'), 'audit_executions', ['id'], unique=False)
    op.create_index(op.f('ix_audit_executions_status'), 'audit_executions', ['status'], unique=False)
    op.create_index(op.f('ix_audit_executions_template_id'), 'audit_executions', ['template_id'], unique=False)
    op.create_table('initial_flow_controls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='项目ID（预留）'),
    sa.Column('material_code', sa.String(length=100), nullable=True, comment='物料编码（预留）'),
    sa.Column('material_name', sa.String(length=200), nullable=True, comment='物料名称（预留）'),
    sa.Column('control_type', sa.Enum('FULL_INSPECTION', 'INCREASED_SAMPLING', 'KEY_DIMENSION_CHECK', 'PROCESS_MONITORING', 'CUSTOM', name='flowcontroltype', native_enum=False, length=50), nullable=True, comment='加严控制类型（预留）'),
    sa.Column('control_config', sa.JSON(), nullable=True, comment='加严控制配置（JSON格式，预留）'),
    sa.Column('exit_criteria', sa.JSON(), nullable=True, comment='退出机制配置（JSON格式，预留）'),
    sa.Column('auto_exit_enabled', sa.Boolean(), nullable=True, comment='是否启用自动退出（预留）'),
    sa.Column('exit_evaluation_data', sa.JSON(), nullable=True, comment='退出评估数据（JSON格式，预留）'),
    sa.Column('status', sa.Enum('ACTIVE', 'MONITORING', 'RELEASED', 'SUSPENDED', name='flowcontrolstatus', native_enum=False, length=20), nullable=True, comment='控制状态（预留）'),
    sa.Column('production_lock_enabled', sa.Boolean(), nullable=True, comment='是否启用生产互锁（预留）'),
    sa.Column('lock_reason', sa.Text(), nullable=True, comment='互锁原因（预留）'),
    sa.Column('start_date', sa.DateTime(), nullable=True, comment='开始日期（预留）'),
    sa.Column('planned_end_date', sa.DateTime(), nullable=True, comment='计划结束日期（预留）'),
    sa.Column('actual_end_date', sa.DateTime(), nullable=True, comment='实际结束日期（预留）'),
    sa.Column('responsible_person_id', sa.Integer(), nullable=True, comment='责任人ID（预留）'),
    sa.Column('approver_id', sa.Integer(), nullable=True, comment='审批人ID（预留）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注（预留）'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['project_id'], ['new_product_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_initial_flow_controls_id'), 'initial_flow_controls', ['id'], unique=False)
    op.create_index(op.f('ix_initial_flow_controls_material_code'), 'initial_flow_controls', ['material_code'], unique=False)
    op.create_index(op.f('ix_initial_flow_controls_project_id'), 'initial_flow_controls', ['project_id'], unique=False)
    op.create_index(op.f('ix_initial_flow_controls_status'), 'initial_flow_controls', ['status'], unique=False)
    op.create_table('msa_records',
    sa.Column('id', sa.Integer(), nullable=False, comment='MSA记录ID'),
    sa.Column('instrument_id', sa.Integer(), nullable=True, comment='关联的仪器ID'),
    sa.Column('msa_type', sa.String(length=50), nullable=True, comment='MSA分析类型: grr/bias/linearity/stability/other'),
    sa.Column('msa_date', sa.Date(), nullable=True, comment='MSA分析日期'),
    sa.Column('msa_result', sa.String(length=20), nullable=True, comment='MSA分析结果: pass/fail/conditional'),
    sa.Column('msa_report_path', sa.String(length=500), nullable=True, comment='MSA分析报告文件路径'),
    sa.Column('grr_percentage', sa.String(length=20), nullable=True, comment='GRR百分比（如适用）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注说明'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人用户ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人用户ID'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_msa_records_id'), 'msa_records', ['id'], unique=False)
    op.create_index(op.f('ix_msa_records_instrument_id'), 'msa_records', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_msa_records_msa_date'), 'msa_records', ['msa_date'], unique=False)
    op.create_index(op.f('ix_msa_records_msa_result'), 'msa_records', ['msa_result'], unique=False)
    op.create_index(op.f('ix_msa_records_msa_type'), 'msa_records', ['msa_type'], unique=False)
    op.create_table('project_lesson_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('lesson_id', sa.Integer(), nullable=False, comment='经验教训ID'),
    sa.Column('is_applicable', sa.Boolean(), nullable=False, comment='是否适用于本项目'),
    sa.Column('reason_if_not', sa.Text(), nullable=True, comment='不适用原因说明'),
    sa.Column('evidence_file_path', sa.String(length=500), nullable=True, comment='规避证据文件路径（设计截图、文件修改记录等）'),
    sa.Column('evidence_description', sa.Text(), nullable=True, comment='规避措施描述'),
    sa.Column('checked_by', sa.Integer(), nullable=True, comment='点检人ID'),
    sa.Column('checked_at', sa.DateTime(), nullable=True, comment='点检时间'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID（阶段评审员）'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('verification_result', sa.String(length=20), nullable=True, comment='验证结果：passed/failed'),
    sa.Column('verification_comment', sa.Text(), nullable=True, comment='验证意见'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson_learned_library.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['new_product_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_lesson_checks_id'), 'project_lesson_checks', ['id'], unique=False)
    op.create_index(op.f('ix_project_lesson_checks_lesson_id'), 'project_lesson_checks', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_project_lesson_checks_project_id'), 'project_lesson_checks', ['project_id'], unique=False)
    op.create_table('quality_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('INCOMING_BATCH_PASS_RATE', 'MATERIAL_ONLINE_PPM', 'PROCESS_DEFECT_RATE', 'PROCESS_FPY', 'OKM_PPM', 'MIS_3_PPM', 'MIS_12_PPM', name='metrictype', native_enum=False, length=50), nullable=False, comment='指标类型'),
    sa.Column('metric_date', sa.Date(), nullable=False, comment='指标日期'),
    sa.Column('value', sa.Numeric(precision=15, scale=4), nullable=False, comment='指标实际值'),
    sa.Column('target_value', sa.Numeric(precision=15, scale=4), nullable=True, comment='指标目标值'),
    sa.Column('product_type', sa.String(length=100), nullable=True, comment='产品类型'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='关联供应商ID'),
    sa.Column('line_id', sa.String(length=50), nullable=True, comment='产线ID'),
    sa.Column('process_id', sa.String(length=50), nullable=True, comment='工序ID'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_metrics_id'), 'quality_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_quality_metrics_line_id'), 'quality_metrics', ['line_id'], unique=False)
    op.create_index(op.f('ix_quality_metrics_metric_date'), 'quality_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_quality_metrics_metric_type'), 'quality_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_quality_metrics_process_id'), 'quality_metrics', ['process_id'], unique=False)
    op.create_index(op.f('ix_quality_metrics_product_type'), 'quality_metrics', ['product_type'], unique=False)
    op.create_index(op.f('ix_quality_metrics_supplier_id'), 'quality_metrics', ['supplier_id'], unique=False)
    op.create_table('stage_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('stage_name', sa.String(length=100), nullable=False, comment='阶段名称（如：概念评审、设计评审、试产评审）'),
    sa.Column('review_date', sa.DateTime(), nullable=True, comment='评审日期'),
    sa.Column('planned_review_date', sa.DateTime(), nullable=True, comment='计划评审日期'),
    sa.Column('deliverables', sa.JSON(), nullable=True, comment='交付物清单（JSON格式）'),
    sa.Column('review_result', sa.Enum('PASSED', 'CONDITIONAL_PASS', 'FAILED', 'PENDING', name='reviewresult', native_enum=False, length=30), nullable=False, comment='评审结果'),
    sa.Column('review_comments', sa.Text(), nullable=True, comment='评审意见'),
    sa.Column('reviewer_ids', sa.String(length=500), nullable=True, comment='评审人ID列表（逗号分隔）'),
    sa.Column('conditional_requirements', sa.Text(), nullable=True, comment='有条件通过时的整改要求'),
    sa.Column('conditional_deadline', sa.DateTime(), nullable=True, comment='整改截止日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['project_id'], ['new_product_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_reviews_id'), 'stage_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_stage_reviews_project_id'), 'stage_reviews', ['project_id'], unique=False)
    op.create_table('supplier_audit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('audit_year', sa.Integer(), nullable=False, comment='审核年度'),
    sa.Column('audit_month', sa.Integer(), nullable=False, comment='计划审核月份'),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='审核类型: system, process, product, qualification'),
    sa.Column('auditor_id', sa.Integer(), nullable=False, comment='审核员ID(SQE)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: planned, in_progress, completed, postponed, cancelled'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_audit_plans_audit_year'), 'supplier_audit_plans', ['audit_year'], unique=False)
    op.create_index(op.f('ix_supplier_audit_plans_id'), 'supplier_audit_plans', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_audit_plans_status'), 'supplier_audit_plans', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_audit_plans_supplier_id'), 'supplier_audit_plans', ['supplier_id'], unique=False)
    op.create_table('supplier_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='文件类型: iso9001, iatf16949, business_license, other'),
    sa.Column('document_name', sa.String(length=255), nullable=False, comment='文件名称'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='文件存储路径'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小(字节)'),
    sa.Column('issue_date', sa.DateTime(), nullable=True, comment='签发日期'),
    sa.Column('expiry_date', sa.DateTime(), nullable=True, comment='到期日期'),
    sa.Column('review_status', sa.String(length=20), nullable=False, comment='审核状态: pending, approved, rejected'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('uploaded_by', sa.Integer(), nullable=True, comment='上传人ID'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_documents_expiry_date'), 'supplier_documents', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_supplier_documents_id'), 'supplier_documents', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_documents_supplier_id'), 'supplier_documents', ['supplier_id'], unique=False)
    op.create_table('supplier_pcns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pcn_number', sa.String(length=50), nullable=False, comment='PCN编号'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('change_type', sa.String(length=50), nullable=False, comment='变更类型: material, process, equipment, location, design'),
    sa.Column('material_code', sa.String(length=100), nullable=True, comment='物料编码'),
    sa.Column('change_description', sa.Text(), nullable=False, comment='变更描述'),
    sa.Column('change_reason', sa.Text(), nullable=False, comment='变更原因'),
    sa.Column('impact_assessment', sa.JSON(), nullable=True, comment='影响评估数据'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='风险等级: low, medium, high'),
    sa.Column('planned_implementation_date', sa.DateTime(), nullable=True, comment='计划实施日期'),
    sa.Column('actual_implementation_date', sa.DateTime(), nullable=True, comment='实际实施日期'),
    sa.Column('cutoff_info', sa.JSON(), nullable=True, comment='断点信息: 旧料最后批次、新料首批次等'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: submitted, under_review, approved, rejected, implemented'),
    sa.Column('current_reviewer_id', sa.Integer(), nullable=True, comment='当前审核人ID'),
    sa.Column('review_comments', sa.JSON(), nullable=True, comment='审核意见记录'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='批准人ID'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='批准时间'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='附件列表: 变更前后对比、测试报告等'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('submitted_by', sa.Integer(), nullable=True, comment='提交人ID'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_pcns_id'), 'supplier_pcns', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_pcns_pcn_number'), 'supplier_pcns', ['pcn_number'], unique=True)
    op.create_index(op.f('ix_supplier_pcns_status'), 'supplier_pcns', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_pcns_supplier_id'), 'supplier_pcns', ['supplier_id'], unique=False)
    op.create_table('trial_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('work_order', sa.String(length=100), nullable=False, comment='IMS工单号'),
    sa.Column('trial_batch', sa.String(length=50), nullable=True, comment='试产批次号'),
    sa.Column('trial_date', sa.DateTime(), nullable=True, comment='试产日期'),
    sa.Column('target_metrics', sa.JSON(), nullable=True, comment='目标指标（JSON格式）'),
    sa.Column('actual_metrics', sa.JSON(), nullable=True, comment='实绩指标（JSON格式）'),
    sa.Column('ims_sync_status', sa.String(length=20), nullable=True, comment='IMS数据同步状态：pending/synced/failed'),
    sa.Column('ims_sync_at', sa.DateTime(), nullable=True, comment='IMS数据同步时间'),
    sa.Column('ims_sync_error', sa.Text(), nullable=True, comment='IMS同步错误信息'),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='trialstatus', native_enum=False, length=20), nullable=False, comment='试产状态'),
    sa.Column('summary_report_path', sa.String(length=500), nullable=True, comment='试产总结报告路径（Excel/PDF）'),
    sa.Column('summary_comments', sa.Text(), nullable=True, comment='试产总结评价'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['project_id'], ['new_product_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_productions_id'), 'trial_productions', ['id'], unique=False)
    op.create_index(op.f('ix_trial_productions_project_id'), 'trial_productions', ['project_id'], unique=False)
    op.create_index(op.f('ix_trial_productions_status'), 'trial_productions', ['status'], unique=False)
    op.create_index(op.f('ix_trial_productions_work_order'), 'trial_productions', ['work_order'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('full_name', sa.String(length=100), nullable=False, comment='姓名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='电话'),
    sa.Column('user_type', sa.Enum('INTERNAL', 'SUPPLIER', name='usertype', native_enum=False, length=20), nullable=False, comment='用户类型'),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FROZEN', 'REJECTED', name='userstatus', native_enum=False, length=20), nullable=False, comment='账号状态'),
    sa.Column('department', sa.String(length=100), nullable=True, comment='部门'),
    sa.Column('position', sa.String(length=100), nullable=True, comment='职位'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='关联供应商ID'),
    sa.Column('digital_signature', sa.String(length=255), nullable=True, comment='电子签名图片路径'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='连续登录失败次数'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='账号锁定截止时间'),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True, comment='密码最后修改时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_supplier_id'), 'users', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_users_user_type'), 'users', ['user_type'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('announcement_read_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='记录ID'),
    sa.Column('announcement_id', sa.Integer(), nullable=False, comment='公告ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='阅读用户ID'),
    sa.Column('read_at', sa.DateTime(), nullable=False, comment='阅读时间'),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'user_id', name='uq_announcement_user')
    )
    op.create_index(op.f('ix_announcement_read_logs_announcement_id'), 'announcement_read_logs', ['announcement_id'], unique=False)
    op.create_index(op.f('ix_announcement_read_logs_id'), 'announcement_read_logs', ['id'], unique=False)
    op.create_index(op.f('ix_announcement_read_logs_user_id'), 'announcement_read_logs', ['user_id'], unique=False)
    op.create_table('audit_ncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False, comment='审核执行记录ID'),
    sa.Column('nc_item', sa.String(length=255), nullable=False, comment='不符合条款'),
    sa.Column('nc_description', sa.Text(), nullable=False, comment='不符合描述'),
    sa.Column('evidence_photo_path', sa.String(length=500), nullable=True, comment='证据照片路径 (多个照片用逗号分隔或JSON格式)'),
    sa.Column('responsible_dept', sa.String(length=100), nullable=False, comment='责任部门'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='指派给(用户ID)'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根本原因'),
    sa.Column('corrective_action', sa.Text(), nullable=True, comment='纠正措施'),
    sa.Column('corrective_evidence', sa.String(length=500), nullable=True, comment='整改证据文件路径'),
    sa.Column('verification_status', sa.String(length=20), nullable=False, comment='验证状态: open, submitted, verified, closed, rejected'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('verification_comment', sa.Text(), nullable=True, comment='验证意见'),
    sa.Column('deadline', sa.DateTime(), nullable=False, comment='整改期限'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['audit_id'], ['audit_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ncs_assigned_to'), 'audit_ncs', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_audit_ncs_audit_id'), 'audit_ncs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_audit_ncs_deadline'), 'audit_ncs', ['deadline'], unique=False)
    op.create_index(op.f('ix_audit_ncs_id'), 'audit_ncs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_ncs_verification_status'), 'audit_ncs', ['verification_status'], unique=False)
    op.create_table('barcode_scan_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False, comment='物料编码'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('batch_number', sa.String(length=100), nullable=True, comment='批次号'),
    sa.Column('barcode_content', sa.String(length=200), nullable=False, comment='条码内容'),
    sa.Column('is_pass', sa.Boolean(), nullable=False, comment='是否通过'),
    sa.Column('error_reason', sa.String(length=500), nullable=True, comment='错误原因'),
    sa.Column('scanned_by', sa.Integer(), nullable=False, comment='扫描人ID'),
    sa.Column('scanned_at', sa.DateTime(), nullable=False, comment='扫描时间'),
    sa.Column('device_ip', sa.String(length=50), nullable=True, comment='设备IP'),
    sa.Column('is_archived', sa.Boolean(), nullable=False, comment='是否已归档'),
    sa.Column('archived_at', sa.DateTime(), nullable=True, comment='归档时间'),
    sa.ForeignKeyConstraint(['scanned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barcode_scan_records_barcode_content'), 'barcode_scan_records', ['barcode_content'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_batch_number'), 'barcode_scan_records', ['batch_number'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_id'), 'barcode_scan_records', ['id'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_is_archived'), 'barcode_scan_records', ['is_archived'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_is_pass'), 'barcode_scan_records', ['is_pass'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_material_code'), 'barcode_scan_records', ['material_code'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_scanned_at'), 'barcode_scan_records', ['scanned_at'], unique=False)
    op.create_index(op.f('ix_barcode_scan_records_supplier_id'), 'barcode_scan_records', ['supplier_id'], unique=False)
    op.create_table('customer_complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_number', sa.String(length=50), nullable=False, comment='客诉单号'),
    sa.Column('complaint_type', sa.Enum('ZERO_KM', 'AFTER_SALES', name='complainttype'), nullable=False, comment='客诉类型：0km/售后'),
    sa.Column('customer_code', sa.String(length=50), nullable=False, comment='客户代码'),
    sa.Column('product_type', sa.String(length=100), nullable=False, comment='产品类型'),
    sa.Column('defect_description', sa.Text(), nullable=False, comment='缺陷描述'),
    sa.Column('severity_level', sa.Enum('CRITICAL', 'MAJOR', 'MINOR', 'TBD', name='severitylevel'), nullable=False, comment='严重度等级'),
    sa.Column('vin_code', sa.String(length=50), nullable=True, comment='VIN码（车架号）'),
    sa.Column('mileage', sa.Integer(), nullable=True, comment='失效里程（公里）'),
    sa.Column('purchase_date', sa.Date(), nullable=True, comment='购车日期'),
    sa.Column('status', sa.Enum('PENDING', 'IN_ANALYSIS', 'IN_RESPONSE', 'IN_REVIEW', 'CLOSED', 'REJECTED', name='complaintstatus'), nullable=False, comment='客诉状态'),
    sa.Column('cqe_id', sa.Integer(), nullable=True, comment='负责CQE的用户ID'),
    sa.Column('responsible_dept', sa.String(length=100), nullable=True, comment='责任部门'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['cqe_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_complaints_complaint_number'), 'customer_complaints', ['complaint_number'], unique=True)
    op.create_index(op.f('ix_customer_complaints_customer_code'), 'customer_complaints', ['customer_code'], unique=False)
    op.create_index(op.f('ix_customer_complaints_id'), 'customer_complaints', ['id'], unique=False)
    op.create_table('inspection_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_code', sa.String(length=100), nullable=False, comment='物料编码'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='版本号'),
    sa.Column('sip_file_path', sa.String(length=500), nullable=True, comment='SIP 文件路径'),
    sa.Column('key_characteristics', sa.JSON(), nullable=True, comment='关键检验项目'),
    sa.Column('report_frequency_type', sa.String(length=20), nullable=True, comment='报告频率类型（batch/weekly/monthly/quarterly）'),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'ARCHIVED', name='inspectionspecstatus', native_enum=False, length=20), nullable=False, comment='状态'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审核人ID（SQE）'),
    sa.Column('review_comments', sa.String(length=1000), nullable=True, comment='审核意见'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='批准时间'),
    sa.Column('effective_date', sa.DateTime(), nullable=True, comment='生效日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID（SQE）'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_specs_effective_date'), 'inspection_specs', ['effective_date'], unique=False)
    op.create_index(op.f('ix_inspection_specs_id'), 'inspection_specs', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_specs_material_code'), 'inspection_specs', ['material_code'], unique=False)
    op.create_index(op.f('ix_inspection_specs_status'), 'inspection_specs', ['status'], unique=False)
    op.create_index(op.f('ix_inspection_specs_supplier_id'), 'inspection_specs', ['supplier_id'], unique=False)
    op.create_table('lesson_learned',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('CUSTOMER_COMPLAINT', 'SUPPLIER_8D', 'PROCESS_ISSUE', 'MANUAL', name='sourcetype'), nullable=False, comment='来源类型'),
    sa.Column('source_id', sa.Integer(), nullable=True, comment='来源记录ID（如客诉单ID、8D报告ID）'),
    sa.Column('lesson_title', sa.String(length=200), nullable=False, comment='经验教训标题'),
    sa.Column('lesson_content', sa.Text(), nullable=False, comment='经验教训详细内容'),
    sa.Column('root_cause', sa.Text(), nullable=False, comment='根本原因'),
    sa.Column('preventive_action', sa.Text(), nullable=False, comment='预防措施'),
    sa.Column('applicable_scenarios', sa.String(length=500), nullable=True, comment='适用场景标签（逗号分隔）'),
    sa.Column('product_types', sa.String(length=200), nullable=True, comment='适用产品类型（逗号分隔）'),
    sa.Column('process_types', sa.String(length=200), nullable=True, comment='适用工序类型（逗号分隔）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用（用于经验教训库管理）'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='批准人ID'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='批准时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_learned_id'), 'lesson_learned', ['id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.Integer(), nullable=False, comment='规则ID'),
    sa.Column('rule_name', sa.String(length=200), nullable=False, comment='规则名称'),
    sa.Column('business_object', sa.String(length=100), nullable=False, comment='业务对象: scar/ppap/audit/customer_complaint等'),
    sa.Column('trigger_condition', sa.JSON(), nullable=False, comment='触发条件JSON: {"field": "status", "operator": "equals", "value": "rejected"}'),
    sa.Column('action_type', sa.String(length=50), nullable=False, comment='动作类型: send_email/send_notification/send_webhook'),
    sa.Column('action_config', sa.JSON(), nullable=False, comment='动作配置JSON: {"recipients": ["user_id"], "template": "rejection_notice"}'),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=False, comment='是否启用超时升级'),
    sa.Column('escalation_hours', sa.Integer(), nullable=True, comment='超时小时数（触发升级）'),
    sa.Column('escalation_recipients', sa.ARRAY(sa.Integer()), nullable=True, comment='升级抄送人ID列表'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_business_object'), 'notification_rules', ['business_object'], unique=False)
    op.create_index(op.f('ix_notification_rules_id'), 'notification_rules', ['id'], unique=False)
    op.create_index(op.f('ix_notification_rules_is_active'), 'notification_rules', ['is_active'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False, comment='通知ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='接收用户ID'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='消息类型: workflow_exception/system_alert/warning'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='消息标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('link', sa.String(length=500), nullable=True, comment='跳转链接（可选）'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_message_type'), 'notifications', ['message_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('operation_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='日志ID'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='操作用户ID（删除用户后保留日志）'),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='操作类型: create/update/delete/login/logout'),
    sa.Column('target_module', sa.String(length=100), nullable=False, comment='目标模块: user/permission/supplier/scar等'),
    sa.Column('target_id', sa.Integer(), nullable=True, comment='目标对象ID（如用户ID、单据ID）'),
    sa.Column('before_data', sa.JSON(), nullable=True, comment='操作前数据快照（JSON格式）'),
    sa.Column('after_data', sa.JSON(), nullable=True, comment='操作后数据快照（JSON格式）'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='客户端IP地址（支持IPv6）'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='浏览器User-Agent'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='操作时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_logs_created_at'), 'operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_operation_logs_id'), 'operation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_operation_logs_operation_type'), 'operation_logs', ['operation_type'], unique=False)
    op.create_index(op.f('ix_operation_logs_target_id'), 'operation_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_operation_logs_target_module'), 'operation_logs', ['target_module'], unique=False)
    op.create_index(op.f('ix_operation_logs_user_id'), 'operation_logs', ['user_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('module_path', sa.String(length=255), nullable=False, comment='功能模块路径（支持多级：一级.二级.三级）'),
    sa.Column('operation_type', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'EXPORT', name='operationtype', native_enum=False, length=20), nullable=False, comment='操作类型'),
    sa.Column('is_granted', sa.Boolean(), nullable=False, comment='是否授予权限'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_path', 'operation_type', name='uq_user_module_operation')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.create_index(op.f('ix_permissions_module_path'), 'permissions', ['module_path'], unique=False)
    op.create_index(op.f('ix_permissions_operation_type'), 'permissions', ['operation_type'], unique=False)
    op.create_index(op.f('ix_permissions_user_id'), 'permissions', ['user_id'], unique=False)
    op.create_table('ppap_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('material_code', sa.String(length=100), nullable=False, comment='物料编码'),
    sa.Column('ppap_level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', 'LEVEL_4', 'LEVEL_5', name='ppaplevel', native_enum=False, length=10), nullable=False, comment='PPAP 提交等级'),
    sa.Column('submission_date', sa.Date(), nullable=True, comment='提交日期'),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'UNDER_REVIEW', 'REJECTED', 'APPROVED', 'EXPIRED', name='ppapstatus', native_enum=False, length=20), nullable=False, comment='状态'),
    sa.Column('documents', sa.JSON(), nullable=True, comment='文件清单'),
    sa.Column('reviewer_id', sa.Integer(), nullable=True, comment='审核人ID（SQE）'),
    sa.Column('review_comments', sa.String(length=1000), nullable=True, comment='审核意见'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='批准时间'),
    sa.Column('revalidation_due_date', sa.Date(), nullable=True, comment='再鉴定到期日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID（SQE）'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ppap_submissions_id'), 'ppap_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_ppap_submissions_material_code'), 'ppap_submissions', ['material_code'], unique=False)
    op.create_index(op.f('ix_ppap_submissions_revalidation_due_date'), 'ppap_submissions', ['revalidation_due_date'], unique=False)
    op.create_index(op.f('ix_ppap_submissions_status'), 'ppap_submissions', ['status'], unique=False)
    op.create_index(op.f('ix_ppap_submissions_submission_date'), 'ppap_submissions', ['submission_date'], unique=False)
    op.create_index(op.f('ix_ppap_submissions_supplier_id'), 'ppap_submissions', ['supplier_id'], unique=False)
    op.create_table('process_defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_date', sa.Date(), nullable=False, comment='不良发生日期'),
    sa.Column('work_order', sa.String(length=100), nullable=False, comment='工单号'),
    sa.Column('process_id', sa.String(length=50), nullable=False, comment='工序ID'),
    sa.Column('line_id', sa.String(length=50), nullable=False, comment='产线ID'),
    sa.Column('defect_type', sa.String(length=200), nullable=False, comment='不良类型/失效模式'),
    sa.Column('defect_qty', sa.Integer(), nullable=False, comment='不良数量'),
    sa.Column('responsibility_category', sa.Enum('MATERIAL_DEFECT', 'OPERATION_DEFECT', 'EQUIPMENT_DEFECT', 'PROCESS_DEFECT', 'DESIGN_DEFECT', name='responsibilitycategory', native_enum=False, length=50), nullable=False, comment='责任类别'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='操作员ID'),
    sa.Column('recorded_by', sa.Integer(), nullable=False, comment='记录人ID'),
    sa.Column('material_code', sa.String(length=100), nullable=True, comment='物料编码'),
    sa.Column('supplier_id', sa.Integer(), nullable=True, comment='供应商ID'),
    sa.Column('remarks', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_defects_defect_date'), 'process_defects', ['defect_date'], unique=False)
    op.create_index(op.f('ix_process_defects_id'), 'process_defects', ['id'], unique=False)
    op.create_index(op.f('ix_process_defects_line_id'), 'process_defects', ['line_id'], unique=False)
    op.create_index(op.f('ix_process_defects_material_code'), 'process_defects', ['material_code'], unique=False)
    op.create_index(op.f('ix_process_defects_process_id'), 'process_defects', ['process_id'], unique=False)
    op.create_index(op.f('ix_process_defects_responsibility_category'), 'process_defects', ['responsibility_category'], unique=False)
    op.create_index(op.f('ix_process_defects_supplier_id'), 'process_defects', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_process_defects_work_order'), 'process_defects', ['work_order'], unique=False)
    op.create_table('process_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=50), nullable=False, comment='问题单编号'),
    sa.Column('issue_description', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('responsibility_category', sa.Enum('MATERIAL_DEFECT', 'OPERATION_DEFECT', 'EQUIPMENT_DEFECT', 'PROCESS_DEFECT', 'DESIGN_DEFECT', name='responsibilitycategory', native_enum=False, length=50), nullable=False, comment='责任类别'),
    sa.Column('assigned_to', sa.Integer(), nullable=False, comment='当前处理人ID'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根本原因分析'),
    sa.Column('containment_action', sa.Text(), nullable=True, comment='围堵措施'),
    sa.Column('corrective_action', sa.Text(), nullable=True, comment='纠正措施'),
    sa.Column('verification_period', sa.Integer(), nullable=True, comment='验证期（天数）'),
    sa.Column('verification_start_date', sa.Date(), nullable=True, comment='验证开始日期'),
    sa.Column('verification_end_date', sa.Date(), nullable=True, comment='验证结束日期'),
    sa.Column('status', sa.Enum('OPEN', 'IN_ANALYSIS', 'IN_VERIFICATION', 'CLOSED', 'CANCELLED', name='processissuestatus', native_enum=False, length=50), nullable=False, comment='问题单状态'),
    sa.Column('related_defect_ids', sa.String(length=500), nullable=True, comment='关联的不良品记录ID'),
    sa.Column('evidence_files', sa.Text(), nullable=True, comment='改善证据附件路径（JSON格式）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='发起人ID'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('closed_by', sa.Integer(), nullable=True, comment='关闭人ID'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_issues_assigned_to'), 'process_issues', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_process_issues_id'), 'process_issues', ['id'], unique=False)
    op.create_index(op.f('ix_process_issues_issue_number'), 'process_issues', ['issue_number'], unique=True)
    op.create_index(op.f('ix_process_issues_responsibility_category'), 'process_issues', ['responsibility_category'], unique=False)
    op.create_index(op.f('ix_process_issues_status'), 'process_issues', ['status'], unique=False)
    op.create_table('scars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scar_number', sa.String(length=50), nullable=False, comment='SCAR 单号'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('material_code', sa.String(length=100), nullable=False, comment='物料编码'),
    sa.Column('defect_description', sa.Text(), nullable=False, comment='缺陷描述'),
    sa.Column('defect_qty', sa.Integer(), nullable=False, comment='不良数量'),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='scarseverity', native_enum=False, length=20), nullable=False, comment='严重度'),
    sa.Column('status', sa.Enum('OPEN', 'SUPPLIER_RESPONDING', 'UNDER_REVIEW', 'REJECTED', 'APPROVED', 'CLOSED', name='scarstatus', native_enum=False, length=30), nullable=False, comment='状态'),
    sa.Column('current_handler_id', sa.Integer(), nullable=True, comment='当前处理人ID'),
    sa.Column('deadline', sa.DateTime(), nullable=False, comment='截止日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['current_handler_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scars_current_handler_id'), 'scars', ['current_handler_id'], unique=False)
    op.create_index(op.f('ix_scars_deadline'), 'scars', ['deadline'], unique=False)
    op.create_index(op.f('ix_scars_id'), 'scars', ['id'], unique=False)
    op.create_index(op.f('ix_scars_material_code'), 'scars', ['material_code'], unique=False)
    op.create_index(op.f('ix_scars_scar_number'), 'scars', ['scar_number'], unique=True)
    op.create_index(op.f('ix_scars_severity'), 'scars', ['severity'], unique=False)
    op.create_index(op.f('ix_scars_status'), 'scars', ['status'], unique=False)
    op.create_index(op.f('ix_scars_supplier_id'), 'scars', ['supplier_id'], unique=False)
    op.create_table('supplier_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_plan_id', sa.Integer(), nullable=True, comment='审核计划ID'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('audit_number', sa.String(length=50), nullable=False, comment='审核编号'),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='审核类型: system, process, product, qualification'),
    sa.Column('audit_date', sa.DateTime(), nullable=False, comment='审核日期'),
    sa.Column('auditor_id', sa.Integer(), nullable=False, comment='主审核员ID'),
    sa.Column('audit_team', sa.JSON(), nullable=True, comment='审核组成员'),
    sa.Column('audit_result', sa.String(length=20), nullable=False, comment='审核结果: passed, conditional_passed, failed'),
    sa.Column('score', sa.Integer(), nullable=True, comment='审核得分'),
    sa.Column('nc_major_count', sa.Integer(), nullable=False, comment='严重不符合项数量'),
    sa.Column('nc_minor_count', sa.Integer(), nullable=False, comment='一般不符合项数量'),
    sa.Column('nc_observation_count', sa.Integer(), nullable=False, comment='观察项数量'),
    sa.Column('audit_report_path', sa.String(length=500), nullable=True, comment='审核报告路径'),
    sa.Column('summary', sa.Text(), nullable=True, comment='审核总结'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态: completed, nc_open, nc_closed'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['supplier_audit_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_audits_audit_date'), 'supplier_audits', ['audit_date'], unique=False)
    op.create_index(op.f('ix_supplier_audits_audit_number'), 'supplier_audits', ['audit_number'], unique=True)
    op.create_index(op.f('ix_supplier_audits_audit_plan_id'), 'supplier_audits', ['audit_plan_id'], unique=False)
    op.create_index(op.f('ix_supplier_audits_id'), 'supplier_audits', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_audits_supplier_id'), 'supplier_audits', ['supplier_id'], unique=False)
    op.create_table('supplier_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='月份'),
    sa.Column('incoming_quality_deduction', sa.Float(), nullable=False, comment='来料质量扣分'),
    sa.Column('process_quality_deduction', sa.Float(), nullable=False, comment='制程质量扣分'),
    sa.Column('cooperation_deduction', sa.Float(), nullable=False, comment='配合度扣分'),
    sa.Column('zero_km_deduction', sa.Float(), nullable=False, comment='0公里/售后质量扣分'),
    sa.Column('total_deduction', sa.Float(), nullable=False, comment='总扣分'),
    sa.Column('final_score', sa.Float(), nullable=False, comment='最终得分（百分制）'),
    sa.Column('grade', sa.Enum('A', 'B', 'C', 'D', name='performancegrade', native_enum=False, length=10), nullable=False, comment='绩效等级'),
    sa.Column('cooperation_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='cooperationlevel', native_enum=False, length=20), nullable=True, comment='配合度等级'),
    sa.Column('cooperation_comment', sa.Text(), nullable=True, comment='配合度评价说明'),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False, comment='是否已人工校核'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='校核人ID（SQE）'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='校核时间'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='校核说明（如核减理由）'),
    sa.Column('manual_adjustment', sa.Float(), nullable=False, comment='人工调整分数（正数为加分，负数为扣分）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='供应商绩效评价表'
    )
    op.create_index(op.f('ix_supplier_performances_grade'), 'supplier_performances', ['grade'], unique=False)
    op.create_index(op.f('ix_supplier_performances_id'), 'supplier_performances', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_performances_month'), 'supplier_performances', ['month'], unique=False)
    op.create_index(op.f('ix_supplier_performances_supplier_id'), 'supplier_performances', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_performances_year'), 'supplier_performances', ['year'], unique=False)
    op.create_table('supplier_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='目标年份'),
    sa.Column('target_type', sa.Enum('INCOMING_PASS_RATE', 'MATERIAL_PPM', 'PROCESS_DEFECT_RATE', 'ZERO_KM_PPM', 'MIS_3_PPM', 'MIS_12_PPM', name='targettype', native_enum=False, length=30), nullable=False, comment='目标类型'),
    sa.Column('target_value', sa.Float(), nullable=False, comment='目标值'),
    sa.Column('is_individual', sa.Boolean(), nullable=False, comment='是否单独设定'),
    sa.Column('is_signed', sa.Boolean(), nullable=False, comment='是否已签署'),
    sa.Column('signed_at', sa.DateTime(), nullable=True, comment='签署时间'),
    sa.Column('signed_by', sa.Integer(), nullable=True, comment='签署人ID（供应商用户）'),
    sa.Column('is_approved', sa.Boolean(), nullable=False, comment='是否已审批'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='审批人ID（质量经理）'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='审批时间'),
    sa.Column('previous_year_actual', sa.Float(), nullable=True, comment='上一年实际达成值'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID（SQE）'),
    sa.Column('updated_by', sa.Integer(), nullable=True, comment='更新人ID'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['signed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='供应商质量目标设定表'
    )
    op.create_index(op.f('ix_supplier_targets_id'), 'supplier_targets', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_targets_is_signed'), 'supplier_targets', ['is_signed'], unique=False)
    op.create_index(op.f('ix_supplier_targets_supplier_id'), 'supplier_targets', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_targets_target_type'), 'supplier_targets', ['target_type'], unique=False)
    op.create_index(op.f('ix_supplier_targets_year'), 'supplier_targets', ['year'], unique=False)
    op.create_table('trial_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False, comment='试产记录ID'),
    sa.Column('issue_number', sa.String(length=50), nullable=True, comment='问题编号'),
    sa.Column('issue_description', sa.Text(), nullable=False, comment='问题描述'),
    sa.Column('issue_type', sa.Enum('DESIGN', 'TOOLING', 'PROCESS', 'MATERIAL', 'EQUIPMENT', 'OTHER', name='issuetype', native_enum=False, length=20), nullable=False, comment='问题类型'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='责任人ID'),
    sa.Column('assigned_dept', sa.String(length=100), nullable=True, comment='责任部门'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根本原因'),
    sa.Column('solution', sa.Text(), nullable=True, comment='解决方案'),
    sa.Column('solution_file_path', sa.String(length=500), nullable=True, comment='对策附件路径'),
    sa.Column('verification_method', sa.Text(), nullable=True, comment='验证方法'),
    sa.Column('verification_result', sa.String(length=20), nullable=True, comment='验证结果：passed/failed'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', name='issuestatus', native_enum=False, length=20), nullable=False, comment='问题状态'),
    sa.Column('is_escalated_to_8d', sa.Boolean(), nullable=False, comment='是否已升级为8D报告'),
    sa.Column('eight_d_id', sa.Integer(), nullable=True, comment='关联的8D报告ID'),
    sa.Column('escalated_at', sa.DateTime(), nullable=True, comment='升级时间'),
    sa.Column('escalation_reason', sa.Text(), nullable=True, comment='升级原因'),
    sa.Column('is_legacy_issue', sa.Boolean(), nullable=False, comment='是否为遗留问题'),
    sa.Column('legacy_approval_status', sa.String(length=20), nullable=True, comment='带病量产审批状态：pending/approved/rejected'),
    sa.Column('legacy_approval_by', sa.Integer(), nullable=True, comment='特批人ID'),
    sa.Column('legacy_approval_at', sa.DateTime(), nullable=True, comment='特批时间'),
    sa.Column('risk_acknowledgement_path', sa.String(length=500), nullable=True, comment='风险告知书路径'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='要求完成时间'),
    sa.Column('resolved_at', sa.DateTime(), nullable=True, comment='解决时间'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['trial_id'], ['trial_productions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_issues_id'), 'trial_issues', ['id'], unique=False)
    op.create_index(op.f('ix_trial_issues_issue_number'), 'trial_issues', ['issue_number'], unique=False)
    op.create_index(op.f('ix_trial_issues_status'), 'trial_issues', ['status'], unique=False)
    op.create_index(op.f('ix_trial_issues_trial_id'), 'trial_issues', ['trial_id'], unique=False)
    op.create_table('customer_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False, comment='关联的客诉单ID'),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='索赔金额'),
    sa.Column('claim_currency', sa.String(length=10), nullable=False, comment='币种（CNY/USD/EUR等）'),
    sa.Column('claim_date', sa.Date(), nullable=False, comment='索赔日期'),
    sa.Column('customer_name', sa.String(length=200), nullable=False, comment='客户名称'),
    sa.Column('claim_description', sa.String(length=500), nullable=True, comment='索赔说明'),
    sa.Column('claim_reference', sa.String(length=100), nullable=True, comment='客户索赔单号'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['complaint_id'], ['customer_complaints.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_claims_complaint_id'), 'customer_claims', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_customer_claims_id'), 'customer_claims', ['id'], unique=False)
    op.create_table('eight_d_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=False, comment='关联的客诉单ID'),
    sa.Column('d0_d3_cqe', sa.JSON(), nullable=True, comment='\n        D0-D3阶段数据（JSON格式）:\n        {\n            "d0_team": ["成员1", "成员2"],  # D0: 组建团队\n            "d1_problem": "问题描述(5W2H)",  # D1: 问题描述\n            "d2_containment": {  # D2: 围堵措施\n                "in_transit": "在途品处理方案",\n                "inventory": "库存品处理方案",\n                "customer_site": "客户端库存处理方案"\n            },\n            "d3_root_cause_initial": "初步原因分析"  # D3: 初步根本原因\n        }\n    '),
    sa.Column('d4_d7_responsible', sa.JSON(), nullable=True, comment='\n        D4-D7阶段数据（JSON格式）:\n        {\n            "d4_root_cause": {  # D4: 根本原因分析\n                "analysis_method": "5Why/鱼骨图/FTA/流程分析",\n                "root_cause": "根本原因描述",\n                "evidence": ["证据文件路径1", "证据文件路径2"]\n            },\n            "d5_corrective_actions": [  # D5: 纠正措施\n                {"action": "措施1", "responsible": "责任人", "deadline": "2024-01-01"}\n            ],\n            "d6_verification": {  # D6: 验证有效性\n                "verification_report": "验证报告文件路径",\n                "test_data": "测试数据文件路径",\n                "result": "验证结果"\n            },\n            "d7_standardization": {  # D7: 标准化\n                "document_modified": true,\n                "modified_files": ["PFMEA更新", "CP更新", "SOP更新"],\n                "attachments": ["文件路径1", "文件路径2"]\n            }\n        }\n    '),
    sa.Column('d8_horizontal', sa.JSON(), nullable=True, comment='\n        D8阶段数据（JSON格式）:\n        {\n            "horizontal_deployment": [  # 水平展开\n                {"product": "类似产品A", "action": "推送对策", "status": "已完成"}\n            ],\n            "lesson_learned": {  # 经验教训\n                "should_archive": true,\n                "lesson_id": 123  # 关联到LessonLearned表的ID\n            }\n        }\n    '),
    sa.Column('status', sa.Enum('DRAFT', 'D0_D3_COMPLETED', 'D4_D7_IN_PROGRESS', 'D4_D7_COMPLETED', 'D8_IN_PROGRESS', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'CLOSED', name='eightdstatus'), nullable=False, comment='8D报告状态'),
    sa.Column('approval_level', sa.Enum('SECTION_MANAGER', 'DEPARTMENT_HEAD', 'NONE', name='approvallevel'), nullable=False, comment='审批级别'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('review_comments', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['complaint_id'], ['customer_complaints.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('complaint_id')
    )
    op.create_index(op.f('ix_eight_d_customer_id'), 'eight_d_customer', ['id'], unique=False)
    op.create_table('eight_d_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scar_id', sa.Integer(), nullable=False, comment='关联的 SCAR ID'),
    sa.Column('d0_d3_data', sa.JSON(), nullable=True, comment='D0-D3 阶段数据'),
    sa.Column('d4_d7_data', sa.JSON(), nullable=True, comment='D4-D7 阶段数据'),
    sa.Column('d8_data', sa.JSON(), nullable=True, comment='D8 阶段数据'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'REJECTED', 'APPROVED', 'CLOSED', name='eightdstatus', native_enum=False, length=20), nullable=False, comment='状态'),
    sa.Column('submitted_by', sa.Integer(), nullable=True, comment='提交人ID'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='审核人ID'),
    sa.Column('review_comments', sa.Text(), nullable=True, comment='审核意见'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('submitted_at', sa.DateTime(), nullable=True, comment='提交时间'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scar_id'], ['scars.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eight_d_reports_id'), 'eight_d_reports', ['id'], unique=False)
    op.create_index(op.f('ix_eight_d_reports_scar_id'), 'eight_d_reports', ['scar_id'], unique=True)
    op.create_index(op.f('ix_eight_d_reports_status'), 'eight_d_reports', ['status'], unique=False)
    op.create_table('supplier_audit_ncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_id', sa.Integer(), nullable=False, comment='审核记录ID'),
    sa.Column('nc_number', sa.String(length=50), nullable=False, comment='NC编号'),
    sa.Column('nc_type', sa.String(length=20), nullable=False, comment='NC类型: major, minor, observation'),
    sa.Column('nc_item', sa.String(length=255), nullable=False, comment='不符合条款'),
    sa.Column('nc_description', sa.Text(), nullable=False, comment='不符合描述'),
    sa.Column('evidence_photos', sa.JSON(), nullable=True, comment='证据照片列表'),
    sa.Column('responsible_dept', sa.String(length=100), nullable=True, comment='责任部门'),
    sa.Column('assigned_to', sa.Integer(), nullable=True, comment='指派给(用户ID)'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='根本原因'),
    sa.Column('corrective_action', sa.Text(), nullable=True, comment='纠正措施'),
    sa.Column('corrective_evidence', sa.JSON(), nullable=True, comment='整改证据'),
    sa.Column('verification_status', sa.String(length=20), nullable=False, comment='验证状态: open, submitted, verified, closed'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='验证人ID'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='验证时间'),
    sa.Column('verification_comment', sa.Text(), nullable=True, comment='验证意见'),
    sa.Column('deadline', sa.DateTime(), nullable=True, comment='整改期限'),
    sa.Column('closed_at', sa.DateTime(), nullable=True, comment='关闭时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['audit_id'], ['supplier_audits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_audit_ncs_assigned_to'), 'supplier_audit_ncs', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_supplier_audit_ncs_audit_id'), 'supplier_audit_ncs', ['audit_id'], unique=False)
    op.create_index(op.f('ix_supplier_audit_ncs_deadline'), 'supplier_audit_ncs', ['deadline'], unique=False)
    op.create_index(op.f('ix_supplier_audit_ncs_id'), 'supplier_audit_ncs', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_audit_ncs_nc_number'), 'supplier_audit_ncs', ['nc_number'], unique=True)
    op.create_index(op.f('ix_supplier_audit_ncs_verification_status'), 'supplier_audit_ncs', ['verification_status'], unique=False)
    op.create_table('supplier_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=True, comment='关联的客诉单ID（可选）'),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('claim_amount', sa.Numeric(precision=15, scale=2), nullable=False, comment='索赔金额'),
    sa.Column('claim_currency', sa.String(length=10), nullable=False, comment='币种（CNY/USD/EUR等）'),
    sa.Column('claim_date', sa.Date(), nullable=False, comment='索赔日期'),
    sa.Column('claim_description', sa.String(length=500), nullable=True, comment='索赔说明'),
    sa.Column('material_code', sa.String(length=50), nullable=True, comment='涉及物料编码'),
    sa.Column('defect_qty', sa.Integer(), nullable=True, comment='不良数量'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_NEGOTIATION', 'ACCEPTED', 'REJECTED', 'PARTIALLY_ACCEPTED', 'PAID', 'CLOSED', name='supplierclaimstatus'), nullable=False, comment='索赔状态'),
    sa.Column('negotiation_notes', sa.String(length=1000), nullable=True, comment='协商记录'),
    sa.Column('final_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='最终索赔金额（协商后）'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='实际支付日期'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['complaint_id'], ['customer_complaints.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_claims_complaint_id'), 'supplier_claims', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_supplier_claims_id'), 'supplier_claims', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_claims_supplier_id'), 'supplier_claims', ['supplier_id'], unique=False)
    op.create_table('supplier_meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False, comment='供应商ID'),
    sa.Column('performance_id', sa.Integer(), nullable=False, comment='关联的绩效评价ID'),
    sa.Column('meeting_number', sa.String(length=50), nullable=False, comment='会议编号'),
    sa.Column('meeting_date', sa.Date(), nullable=True, comment='会议日期'),
    sa.Column('performance_grade', sa.String(length=10), nullable=False, comment='触发会议的绩效等级（C或D）'),
    sa.Column('required_attendee_level', sa.String(length=50), nullable=False, comment='要求参会人员级别（C级:副总级，D级:总经理）'),
    sa.Column('improvement_report_path', sa.String(length=500), nullable=True, comment='物料品质问题改善报告路径'),
    sa.Column('report_uploaded_at', sa.DateTime(), nullable=True, comment='报告上传时间'),
    sa.Column('report_uploaded_by', sa.Integer(), nullable=True, comment='报告上传人ID（供应商用户）'),
    sa.Column('actual_attendee_level', sa.String(length=50), nullable=True, comment='实际参会最高级别人员'),
    sa.Column('attendee_name', sa.String(length=100), nullable=True, comment='参会人员姓名'),
    sa.Column('attendee_position', sa.String(length=100), nullable=True, comment='参会人员职位'),
    sa.Column('meeting_minutes', sa.Text(), nullable=True, comment='会议纪要'),
    sa.Column('supplier_attended', sa.Boolean(), nullable=False, comment='供应商是否参会'),
    sa.Column('report_submitted', sa.Boolean(), nullable=False, comment='是否提交改善报告'),
    sa.Column('penalty_applied', sa.Boolean(), nullable=False, comment='是否已执行违规处罚（下月配合度扣分）'),
    sa.Column('penalty_reason', sa.Text(), nullable=True, comment='处罚原因'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：pending-待召开，completed-已完成，cancelled-已取消'),
    sa.Column('recorded_by', sa.Integer(), nullable=True, comment='记录人ID（SQE）'),
    sa.Column('recorded_at', sa.DateTime(), nullable=True, comment='记录时间'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performance_id'], ['supplier_performances.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_uploaded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='供应商会议记录表'
    )
    op.create_index(op.f('ix_supplier_meetings_id'), 'supplier_meetings', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_meetings_meeting_number'), 'supplier_meetings', ['meeting_number'], unique=True)
    op.create_index(op.f('ix_supplier_meetings_performance_id'), 'supplier_meetings', ['performance_id'], unique=False)
    op.create_index(op.f('ix_supplier_meetings_status'), 'supplier_meetings', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_meetings_supplier_id'), 'supplier_meetings', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError(
        "This migration is intentionally forward-only. "
        "Destructive downgrade operations are disabled by repository policy."
    )
